#line 2 "r86.c"

#line 4 "r86.c"

#pragma warning(disable : 4996)

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

///* Limits of integral types. */
//#ifndef INT8_MIN
//#define INT8_MIN               (-128)
//#endif
//#ifndef INT16_MIN
//#define INT16_MIN              (-32767-1)
//#endif
//#ifndef INT32_MIN
//#define INT32_MIN              (-2147483647-1)
//#endif
//#ifndef INT8_MAX
//#define INT8_MAX               (127)
//#endif
//#ifndef INT16_MAX
//#define INT16_MAX              (32767)
//#endif
//#ifndef INT32_MAX
//#define INT32_MAX              (2147483647)
//#endif
//#ifndef UINT8_MAX
//#define UINT8_MAX              (255U)
//#endif
//#ifndef UINT16_MAX
//#define UINT16_MAX             (65535U)
//#endif
//#ifndef UINT32_MAX
//#define UINT32_MAX             (4294967295U)
//#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 49
#define YY_END_OF_BUFFER 50
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[244] =
    {   0,
       50,   48,   49,   47,   48,   49,   47,   49,   48,   49,
       48,   49,   10,   48,   49,    2,   48,   49,   48,   49,
       10,   48,   49,   10,   48,   49,    1,   47,   48,   49,
        5,   49,    4,   49,    4,    5,   49,    1,    5,   49,
       47,   48,   49,    6,   47,   49,    6,   48,   49,   48,
       49,   48,   49,   48,   49,   48,   49,   44,   48,   49,
       30,   48,   49,   30,   48,   49,    3,   48,   49,   48,
       49,   30,   44,   48,   49,   44,   48,   49,   48,   49,
       30,   44,   48,   49,   44,   48,   49,    1,   47,   48,
       49,   47,   48,   49,   48,   49,   48,   49,   48,   49,

       48,   49,   48,   49,   48,   49,   48,   49,   48,   49,
        1,   47,   48,   49,   49,   22,   49,    1,   49,   23,
       48,   49,   48,   49,   48,   49,   28,   48,   49,   24,
       48,   49,   24,   48,   49,   48,   49,   29,   48,   49,
       49,    6,   49,   49,   45,   49,    3,   49,   49,    1,
       49,   47,   47,   10,    2,   10,   10,   10,16430,   10,
       10,    1,   47,    1,   47,    3,   38,   42,   42,   44,
       30,   30,   31,   43,16430,   30,   44,   39,   44,   41,
       44,   40,   44,    1,   47,   16,   20,   20,   21,   17,
       19,   18,    1,   47,   22,   25,   27,   27,   24,   26,

       45,    1, 8238,16430,    9,   10,   38,   43,16430,   16,
       21,   25,    8,    7, 8238,   32,   33,   37,   34,   36,
       35,   11,   15,   12,   14,   13,    8,    8,    8,    7,
        8,    7,    7,    7,    7,    8,    7,    8,    7,    8,
        7,    7,    8
    } ;

static yyconst flex_int16_t yy_accept[206] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   11,   13,   16,   19,   21,   24,   27,   31,   33,
       35,   38,   41,   44,   47,   50,   52,   54,   56,   58,
       61,   64,   67,   70,   72,   76,   79,   81,   85,   88,
       92,   95,   97,   99,  101,  103,  105,  107,  109,  111,
      115,  116,  118,  120,  123,  125,  127,  130,  133,  136,
      138,  141,  142,  144,  145,  147,  149,  150,  152,  153,
      154,  154,  154,  155,  156,  156,  157,  158,  158,  159,
      160,  161,  162,  164,  165,  166,  166,  167,  168,  169,

      170,  170,  171,  171,  172,  173,  174,  174,  176,  178,
      180,  180,  180,  180,  180,  180,  182,  184,  186,  187,
      188,  189,  189,  190,  191,  191,  191,  191,  191,  191,
      192,  193,  195,  196,  197,  198,  199,  200,  200,  201,
      201,  202,  203,  203,  203,  203,  204,  205,  207,  208,
      208,  208,  208,  210,  210,  210,  210,  210,  210,  210,
      211,  211,  211,  212,  212,  212,  212,  212,  212,  212,
      213,  213,  213,  214,  214,  215,  216,  217,  217,  218,
      219,  219,  220,  221,  222,  222,  223,  224,  224,  225,
      226,  227,  228,  229,  230,  232,  233,  234,  235,  237,

      239,  241,  242,  244,  244
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    1,    7,    8,    1,    1,    1,
        1,    9,   10,   11,   12,   13,    1,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,    1,
       18,    1,   19,    1,   20,   21,   21,   21,   22,   21,
       23,   23,   23,   23,   23,   24,   23,   23,   23,   23,
       23,   25,   23,   23,   23,   23,   23,   23,   23,   23,
       26,    1,   27,    1,   23,    1,   28,   29,   21,   21,

       30,   31,   23,   23,   23,   23,   23,   32,   23,   23,
       23,   33,   23,   25,   34,   23,   23,   23,   23,   35,
       23,   23,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[36] =
    {   0,
        1,    2,    3,    1,    2,    4,    1,    1,    1,    1,
        1,    1,    5,    6,    6,    4,    1,    2,    1,    7,
        7,    7,    5,    5,    5,    1,    8,    7,    7,    7,
        7,    5,    5,    5,    9
    } ;

static yyconst flex_int16_t yy_base[240] =
    {   0,
        0,   34,   34,   38,   43,   77,   81,  114,  445,   85,
       99,  106,  148,   89,  182,  118,  455,  627,  200,  124,
      129,    0,    0,  627,    0,  431,  420,  136,  627,  627,
      627,  140,  234,  187,  627,  192,    0,  434,   66,    0,
      241,  412,  627,    0,  264,  287,  239,  413,  412,  142,
      209,    0,  430,  403,    0,    0,  298,  404,  396,  213,
      627,  421,  236,  627,    0,  403,  627,  379,  377,    0,
      627,  323,  627,  243,  400,  627,    0,  328,    0,  278,
      333,    0,    0,  627,    0,  382,  367,  339,    0,   87,
      375,  364,  341,  346,    0,  347,  627,    0,  355,    0,

       84,    0,   98,  352,    0,  627,  377,  108,    0,    0,
        0,  365,    0,  345,  344,    0,    0,    0,    0,  338,
        0,  363,    0,    0,    0,  352,    0,  328,  327,  627,
      627,  353,  349,    0,  302,    0,  301,  192,    0,  357,
      326,  363,  365,  370,  379,  133,  236,    0,    0,    0,
      243,  312,  297,  297,  169,  287,  277,  255,  223,    0,
        0,  212,    0,  183,  232,  181,  168,  164,  103,    0,
        0,   91,  384,  229,  387,  262,  627,   65,  627,  627,
        0,  627,  627,  627,   58,  627,  627,    0,  627,  627,
      627,    0,  401,  276,  394,  396,  409,  627,  405,  418,

        0,  420,  427,  627,  461,  470,  479,  484,  489,  494,
      499,  503,  506,  511,  516,  520,  523,  527,  530,  534,
      536,  540,  546,  552,  557,  561,  565,  570,  574,  576,
      579,  584,  589,  593,  595,  598,  603,  608,  617
    } ;

static yyconst flex_int16_t yy_def[240] =
    {   0,
      204,    1,  205,  205,  204,    5,  206,  206,  207,  207,
      206,  206,  204,   13,  207,   15,  204,  204,  204,  204,
      204,  208,  209,  204,  210,  209,  209,   19,  204,  204,
      204,  204,  204,  204,  204,  204,  211,  212,  204,  213,
      204,   41,  204,  214,  204,  204,  204,   45,  213,   33,
      204,  215,  216,  204,  217,  218,  204,  204,  204,  204,
      204,  204,  204,  204,  219,  220,  204,  221,  221,  222,
      204,  204,  204,  204,  204,  204,  210,  204,   19,  204,
      204,  208,  209,  204,  210,  209,  209,  223,  209,  224,
      209,  209,   19,  204,   33,  204,  204,  225,  212,  212,

      204,  213,  204,   41,  226,  204,  226,  227,   45,   46,
      228,  229,  230,  204,  204,  213,  213,   50,  231,  216,
      216,  204,  232,  218,  233,  234,  235,  204,  204,  204,
      204,  204,  204,  236,  220,  220,  221,  221,  222,  204,
      204,  204,  204,  223,  204,  204,  224,  209,  225,  212,
      204,  212,  227,  237,  229,  229,  230,  204,  204,  231,
      216,  216,  232,  238,  234,  234,  235,  204,  204,  236,
      220,  220,  239,  204,  204,  204,  204,  237,  204,  204,
      229,  204,  204,  204,  238,  204,  204,  234,  204,  204,
      204,  239,  239,  239,  239,  204,  204,  204,  239,  239,

      239,  204,  239,    0,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204
    } ;

static yyconst flex_int16_t yy_nxt[663] =
    {   0,
       18,   19,   20,   18,   19,   21,   22,   18,   18,   18,
       18,   18,   23,   18,   18,   18,   24,   18,   25,   23,
       23,   23,   23,   26,   23,   18,   18,   23,   23,   23,
       23,   27,   23,   23,   23,   28,   30,   31,   28,   32,
       30,   31,   32,   18,   33,   34,   35,   33,   36,   37,
       38,   18,   18,   18,   39,   40,   41,   42,   18,   43,
       18,   44,   45,   45,   45,   40,   40,   46,   47,   18,
       45,   48,   45,   45,   40,   40,   49,   40,   50,  101,
      101,   50,   51,   20,  186,   51,   63,   52,   53,   63,
       60,  179,  146,   60,   54,   62,  103,  101,  101,   55,

       51,   20,  146,   51,  135,   56,   57,   60,   20,   58,
       60,  151,  151,  146,   59,   60,   20,  106,   60,   78,
       52,   53,   78,  146,   64,   80,   80,   54,   80,  191,
       81,   64,   55,   81,   81,  176,  176,   93,   56,   57,
       93,   94,   58,  118,   94,   84,  118,   59,   18,   51,
       20,   18,   51,   18,   65,   66,   67,   67,   18,   67,
       18,   68,   69,   18,   18,   18,   18,   69,   69,   69,
       18,   18,   70,   18,   71,   69,   69,   69,   69,   18,
       18,   18,   18,   72,   73,   73,   72,   74,   80,   80,
      190,   80,   75,   96,  189,  180,   96,   96,   76,  172,

       77,   79,   80,  181,   79,   81,   82,  187,   97,  186,
       80,   80,   83,   80,  132,   80,   84,  132,   85,   83,
       83,   83,   83,   86,   83,  120,  204,   83,   83,   83,
       83,   87,   83,   83,   83,   95,   80,   94,   95,   96,
       94,  146,  175,  175,   96,  111,  112,   96,   96,  184,
       97,  146,   85,  103,  104,  104,  151,  151,  187,   97,
      105,  105,  105,  113,  176,  176,  188,  114,  105,  105,
      105,  105,  115,  177,  106,  107,  102,  109,  109,   80,
       80,  183,   80,  109,  109,  109,  102,  102,  102,  195,
      195,  109,  109,  109,  109,  102,  102,  102,  102,  102,

      110,  110,  146,  182,  125,  126,  110,  110,  110,  102,
      102,  102,  146,  180,  110,  110,  110,  110,  102,  102,
      102,  102,  127,  179,  140,   99,  128,  140,   96,  142,
      141,  129,  142,   96,   81,  204,  171,   81,   81,   97,
      143,   85,   93,  143,   97,   93,   85,   94,   96,   84,
       94,   96,   96,  133,  132,   80,  145,  132,  140,  169,
      168,  140,   96,   97,  142,  165,  143,  142,   96,  143,
      162,  143,  161,   97,  143,   85,  159,  158,  155,   97,
      173,   85,  145,  173,  152,  193,  204,  145,  193,  150,
      174,  148,  175,  175,  148,  194,   92,  195,  195,  196,

      197,  197,  193,   91,  141,  193,  199,  200,  200,  202,
      202,  204,  194,  138,  195,  195,  135,  198,  203,  203,
      198,  196,  197,  197,  201,  133,  198,  201,  131,  198,
      199,  200,  200,  202,  202,  201,  130,  122,  201,  198,
      203,  203,  198,  120,  117,  116,  204,   99,  201,   92,
      198,  201,   91,  198,  204,   62,  204,  201,  204,  204,
      201,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   88,  204,
       88,  204,   88,   89,   89,   89,  204,   89,   90,  204,

       90,  204,   90,   98,  204,   98,  204,   98,  100,  100,
      102,  102,  102,  204,  102,  108,  204,  108,  204,  108,
      119,  204,  119,  204,  119,  121,  121,  123,  204,  123,
      204,  123,  124,  124,  134,  204,  134,  204,  134,  136,
      136,  137,  137,  204,  137,  139,  139,  144,  204,  204,
      144,  144,  144,  204,  144,  147,  147,  147,  147,  204,
      147,  149,  149,  149,  204,  149,  105,  105,  153,  153,
      153,  153,  204,  153,  154,  204,  154,  204,  154,  156,
      156,  157,  157,  160,  160,  160,  204,  160,  163,  163,
      163,  204,  163,  164,  204,  164,  204,  164,  166,  166,

      167,  167,  170,  170,  170,  204,  170,  178,  178,  178,
      178,  178,  185,  185,  185,  185,  185,  192,  192,  204,
      192,  192,  192,  192,  192,  192,   17,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204
    } ;

static yyconst flex_int16_t yy_chk[663] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    3,    3,    2,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    6,   39,
       39,    6,    7,    7,  185,    7,   10,    7,    7,   10,
       14,  178,   90,   14,    7,   10,  101,  101,  101,    7,

       11,   11,   90,   11,  172,    7,    7,   12,   12,    7,
       12,  103,  103,  108,    7,    8,    8,  101,    8,   16,
        8,    8,   16,  108,   11,   20,   20,    8,   20,  169,
       21,   12,    8,   21,   21,  146,  146,   28,    8,    8,
       28,   32,    8,   50,   32,   21,   50,    8,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   15,   15,   15,   15,   15,   34,   34,
      168,   34,   15,   36,  167,  155,   36,   36,   15,  138,

       15,   19,   19,  155,   19,   19,   19,  166,   36,  164,
       51,   51,   19,   51,   60,   60,   19,   60,   19,   19,
       19,   19,   19,   19,   19,  162,  138,   19,   19,   19,
       19,   19,   19,   19,   19,   33,   33,   63,   33,   33,
       63,  147,  174,  174,   74,   47,   47,   74,   74,  159,
       33,  147,   33,   41,   41,   41,  151,  151,  165,   74,
       41,   41,   41,   47,  176,  176,  165,   47,   41,   41,
       41,   41,   47,  151,   41,   41,   45,   45,   45,   80,
       80,  158,   80,   45,   45,   45,   45,   45,   45,  194,
      194,   45,   45,   45,   45,   45,   45,   45,   45,   46,

       46,   46,  153,  157,   57,   57,   46,   46,   46,   46,
       46,   46,  153,  156,   46,   46,   46,   46,   46,   46,
       46,   46,   57,  154,   72,  152,   57,   72,   72,   78,
      141,   57,   78,   78,   81,  137,  135,   81,   81,   72,
       88,   72,   93,   88,   78,   93,   78,   94,   96,   81,
       94,   96,   96,  133,  132,  132,   88,  132,  140,  129,
      128,  140,  140,   96,  142,  126,  143,  142,  142,  143,
      122,  144,  120,  140,  144,  140,  115,  114,  112,  142,
      145,  142,  143,  145,  107,  173,  104,  144,  173,   99,
      145,   92,  145,  145,   91,  173,   87,  173,  173,  175,

      175,  175,  193,   86,   75,  193,  195,  195,  195,  196,
      196,   69,  193,   68,  193,  193,   66,  175,  199,  199,
      175,  197,  197,  197,  195,   62,  196,  195,   59,  196,
      200,  200,  200,  202,  202,  199,   58,   54,  199,  197,
      203,  203,  197,   53,   49,   48,   42,   38,  200,   27,
      202,  200,   26,  202,   17,    9,    0,  203,    0,    0,
      203,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  208,    0,
      208,    0,  208,  209,  209,  209,    0,  209,  210,    0,

      210,    0,  210,  211,    0,  211,    0,  211,  212,  212,
      213,  213,  213,    0,  213,  214,    0,  214,    0,  214,
      215,    0,  215,    0,  215,  216,  216,  217,    0,  217,
        0,  217,  218,  218,  219,    0,  219,    0,  219,  220,
      220,  221,  221,    0,  221,  222,  222,  223,    0,    0,
      223,  223,  223,    0,  223,  224,  224,  224,  224,    0,
      224,  225,  225,  225,    0,  225,  226,  226,  227,  227,
      227,  227,    0,  227,  228,    0,  228,    0,  228,  229,
      229,  230,  230,  231,  231,  231,    0,  231,  232,  232,
      232,    0,  232,  233,    0,  233,    0,  233,  234,  234,

      235,  235,  236,  236,  236,    0,  236,  237,  237,  237,
      237,  237,  238,  238,  238,  238,  238,  239,  239,    0,
      239,  239,  239,  239,  239,  239,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[50] =
    {   0,
0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 1, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "r86.flex"
/* Tokenizer for the Raptor86 Assembler */
#line 4 "r86.flex"
	#include <stdio.h>
	#include "Tokenizer.h"

	#define isatty

	using namespace InputTypes;

	//<OPCODE_SPECIFIED>{DEREFERECE_ARITHMETIC}/","				BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_DF_SPECIAL_PTR );
	//LEA_INPUT													[ \t]*("lea"|"LEA")[ ]*{ID}","[ ]*"[".+"]"







#line 761 "r86.c"

#define INITIAL 0
#define COMMENT 1
#define OPCODE_SPECIFIED 2
#define LEA_SPECIFIED 3
#define LEA_COMMA 4
#define LEA_SECOND_ARGUMENT 5
#define LEA_INTERNAL 6
#define NEXT_EXPECTED 7

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 55 "r86.flex"


#line 981 "r86.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 205 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 627 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 57 "r86.flex"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 59 "r86.flex"
BEGIN( COMMENT );
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 60 "r86.flex"
BEGIN( COMMENT );
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 61 "r86.flex"
BEGIN( INITIAL );
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 62 "r86.flex"

	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 64 "r86.flex"
BEGIN( INITIAL ); ParseInput( yytext, INPUT_NEW_LINE );
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "r86.flex"
ParseInput( yytext, INPUT_GVAR );
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 67 "r86.flex"
ParseInput( yytext, INPUT_GVAR );
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "r86.flex"
BEGIN( LEA_SPECIFIED ); ParseInput( yytext, INPUT_LEA_INSTRUCTION );
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "r86.flex"
BEGIN( OPCODE_SPECIFIED ); ParseInput( yytext, INPUT_INSTRUCTION );
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 72 "r86.flex"
BEGIN( LEA_COMMA );	ParseInput( yytext, INPUT_OPERAND_DF_GVAR );
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 73 "r86.flex"
BEGIN( LEA_COMMA );	ParseInput( yytext, INPUT_OPERAND_DF_REGISTER );
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 74 "r86.flex"
BEGIN( LEA_COMMA );	ParseInput( yytext, INPUT_OPERAND_DF_STACK_PTR );
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 75 "r86.flex"
BEGIN( LEA_COMMA );	ParseInput( yytext, INPUT_OPERAND_DF_BASE_PTR );
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 76 "r86.flex"
BEGIN( LEA_COMMA );	ParseInput( yytext, INPUT_OPERAND_DF_ADDRESS );
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "r86.flex"
BEGIN( LEA_COMMA );	ParseInput( yytext, INPUT_OPERAND_GVAR );
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "r86.flex"
BEGIN( LEA_COMMA );	ParseInput( yytext, INPUT_OPERAND_REGISTER );
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "r86.flex"
BEGIN( LEA_COMMA );	ParseInput( yytext, INPUT_OPERAND_STACK_PTR );
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "r86.flex"
BEGIN( LEA_COMMA );	ParseInput( yytext, INPUT_OPERAND_BASE_PTR );
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "r86.flex"
BEGIN( LEA_COMMA );	ParseInput( yytext, INPUT_OPERAND_ADDRESS );
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "r86.flex"
BEGIN( LEA_COMMA );	ParseInput( yytext, INPUT_OPERAND_LABEL );
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 85 "r86.flex"
BEGIN( LEA_SECOND_ARGUMENT );
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 86 "r86.flex"
BEGIN( LEA_INTERNAL ); ParseInput( yytext, INPUT_LEA_INTERNAL );
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "r86.flex"
BEGIN( LEA_INTERNAL );	ParseInput( yytext, INPUT_OPERAND_UINT );
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 89 "r86.flex"
BEGIN( LEA_INTERNAL );	ParseInput( yytext, INPUT_OPERAND_GVAR );
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 90 "r86.flex"
BEGIN( LEA_INTERNAL );	ParseInput( yytext, INPUT_OPERAND_REGISTER );
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 91 "r86.flex"
BEGIN( LEA_INTERNAL );	ParseInput( yytext, INPUT_OPERAND_ADDRESS );
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 92 "r86.flex"
BEGIN( LEA_INTERNAL );	ParseInput( yytext, INPUT_LEA_MATH );
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 93 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_UNKNOWN );
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 95 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_UINT );
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 96 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_INT );
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 97 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_FLOAT );
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 99 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_DF_GVAR );
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 100 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_DF_REGISTER );
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 101 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_DF_STACK_PTR );
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 102 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_DF_BASE_PTR );
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 103 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_DF_ADDRESS );
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 105 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_GVAR );
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 106 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_REGISTER );
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 107 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_STACK_PTR );
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 108 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_BASE_PTR );
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 109 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_ADDRESS );
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 110 "r86.flex"
BEGIN( NEXT_EXPECTED );	ParseInput( yytext, INPUT_OPERAND_LABEL );
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 112 "r86.flex"
BEGIN( OPCODE_SPECIFIED );	ParseInput( yytext, INPUT_INSTRUCTION );
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 114 "r86.flex"
BEGIN( OPCODE_SPECIFIED );
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 116 "r86.flex"
BEGIN( INITIAL ); ParseInput( yytext, INPUT_LABEL );					
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 118 "r86.flex"

	YY_BREAK
case 48:
YY_RULE_SETUP
#line 120 "r86.flex"

	YY_BREAK
case 49:
YY_RULE_SETUP
#line 122 "r86.flex"
ECHO;
	YY_BREAK
#line 1321 "r86.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(OPCODE_SPECIFIED):
			case YY_STATE_EOF(LEA_SPECIFIED):
			case YY_STATE_EOF(LEA_COMMA):
			case YY_STATE_EOF(LEA_SECOND_ARGUMENT):
			case YY_STATE_EOF(LEA_INTERNAL):
			case YY_STATE_EOF(NEXT_EXPECTED):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 205 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 205 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 204);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 122 "r86.flex"



void ParseR86File( char* fileName )
{
	yyin = fopen( fileName, "r" );
	yylex();

	fclose( yyin );
}
